### ISSUE TITLE
请问怎么关掉开机自动重启或者卸载它

### ISSUE THREAD

**Issue by gonefuture** [dingdang-robot/dingdang-robot#106]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/dingdang-robot/dingdang-robot/issues) 页、[常见问题](https://github.com/dingdang-robot/dingdang-robot/wiki/troubleshooting)页、[论坛](http://bbs.hahack.com) 中都查找过，没有找到类似问题。我也没有 google / bing/ 百度 / duckduckgo 到相关问题。

**安装方式**

手动安装/镜像安装

**操作系统**

（例如 Raspbian Stretch）

**问题描述**

具体说明下问题

**复现步骤**

具体描述下复现步骤

**Comment by wzpan** [comment]
什么叫做关机自动重启？关机是关机，重启是重启。

**Comment by gonefuture** [comment]
你好. 就是我刷了镜像后,现在树莓派每次开机,叮当就自动启动.我想不自动启动,改成手动启动,或者暂时卸载叮当.

**Comment by wzpan** [comment]
@gonefuture 参见[这篇文章](http://forum.sourcecc.io/topic/85/%E8%AE%BE%E7%BD%AE%E5%BC%80%E6%9C%BA%E5%90%AF%E5%8A%A8)，去掉 dingdang.desktop 文件即可。
