### ISSUE TITLE
修改client/plugins/下的SendQR.py

### ISSUE THREAD

**Issue by Lawrenceguo** [dingdang-robot/dingdang-robot#109]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/dingdang-robot/dingdang-robot/issues) 页、[常见问题](https://github.com/dingdang-robot/dingdang-robot/wiki/troubleshooting)页、[论坛](http://bbs.hahack.com) 中都查找过，没有找到类似问题。我也没有 google / bing/ 百度 / duckduckgo 到相关问题。

**安装方式**

镜像安装

**操作系统**

Raspbian Stretch

**问题描述**

修改client/plugins/下的SendQR.py文件，修改完之后重新运行dingdang.py，修改部分无响应

**复现步骤**

具体描述下复现步骤

**Comment by wzpan** [comment]
这个为什么提bug？

**Comment by Lawrenceguo** [comment]
是这样，我对client/plugins/下的SendQR.py文件进行了一些修改，如：
对这样的提示与进行了修改，还有其他部分的修改，但重新运行dingdang.py后发现，没有按照我修改的部分运行，还是原来的，似乎修改错了文件?

发送自 Windows 10 版邮件应用

发件人: HaHack
发送时间: 2018年10月31日 19:42
收件人: dingdang-robot/dingdang-robot
抄送: Lawrence; Author
主题: Re: [dingdang-robot/dingdang-robot] 修改client/plugins/下的SendQR.py (#109)

这个为什么提bug？
