### ISSUE TITLE
为什么运行叮当以后什么错误也没提示就直接结束了

### ISSUE THREAD

**Issue by mapenghui03** [dingdang-robot/dingdang-robot#15]
python dingdang.py

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`

**Comment by Conrad-hui** [comment]
你好，你的问题解决了么

**Comment by wzpan** [comment]
如需查看log，可以执行 tail -f 叮当所在目录/temp/dingdang.log

**Comment by mapenghui03** [comment]
运行叮当以后开始出现这个错误

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`


Traceback (most recent call last):
  File "dingdang.py", line 154, in <module>
    level=logging.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/pi/dingdang/temp/dingdang.log'
然后我创建了一个temp文件夹  之后运行叮当这个错误消失了但是叮当 马上就结束了

**Comment by wzpan** [comment]
我估计你是先用了root方式运行了dingdang，又改成了普通用户。把 temp 目录完全删掉再试。

**Comment by Conrad-hui** [comment]
我和他的问题应该是一样的，删掉就会出现那个错误

**Comment by mapenghui03** [comment]
这个问题解决了重新安装了一下Pocketsphinx就行了不过出现了个新问题

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`


Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "dingdang.py", line 178, in <module>
    app.run()
  File "dingdang.py", line 124, in run
    self.mic.say(salutation, cache=True)
  File "/home/pi/dingdang/client/mic.py", line 335, in say
    self.speaker.say(phrase, cache)
  File "/home/pi/dingdang/client/tts.py", line 133, in say
    tmpfile = self.get_speech(phrase)
  File "/home/pi/dingdang/client/tts.py", line 409, in get_speech
    signature = self.to_sha1_base64(stringToSign, self.ak_secret)
  File "/home/pi/dingdang/client/tts.py", line 382, in to_sha1_base64
    hmacsha1 = hmac.new(secret, stringToSign, hashlib.sha1)
  File "/usr/lib/python2.7/hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode
这是怎么回事该怎么解决

**Comment by wzpan** [comment]
参见 #2 。更新叮当试试，还不行的话换成其他stt。
