### ISSUE TITLE
 mic.py[line:299]             ERROR read() got an unexpected keyword argument 'exception_on_overflow'

### ISSUE THREAD

**Issue by breeef** [dingdang-robot/dingdang-robot#3]
mic.py[line:299]             ERROR read() got an unexpected keyword argument 'exception_on_overflow'
这个错怎么办，有思路吗

**Comment by wzpan** [comment]
在常见问题解答里搜：https://github.com/dingdang-robot/dingdang-robot/wiki/troubleshooting
