### ISSUE TITLE
启动失败，没提示，没有错误，日志文件打不开！

### ISSUE THREAD

**Issue by chinaboy2277** [dingdang-robot/dingdang-robot#30]
pi@raspberrypi:~/dingdang $ python dingdang.py

*******************************************************"
*             叮当 - 中文语音对话机器人               *
*          (c) 2017 潘伟洲 <m@hahack.com>             *
*   https://github.com/wzpan/dingdang-robot.git       *
*******************************************************

如需查看log，可以执行 `tail -f 叮当所在目录/temp/dingdang.log`

**Comment by chinaboy2277** [comment]
pi@raspberrypi:~ $ tail -f /temp/dingdang.log
tail: 无法打开'/temp/dingdang.log' 读取数据: 没有那个文件或目录
tail: 没有剩余文件
pi@raspberrypi:~ $ cd temp
-bash: cd: temp: 没有那个文件或目录
pi@raspberrypi:~ $  tail -f temp
tail: 无法打开'temp' 读取数据: 没有那个文件或目录
tail: 没有剩余文件
pi@raspberrypi:~ $ tail -f ～/dingdang/dingdang.log
tail: 无法打开'～/dingdang/dingdang.log' 读取数据: 没有那个文件或目录
tail: 没有剩余文件
pi@raspberrypi:~ $ tail -f /dingdang/dingdang.log
tail: 无法打开'/dingdang/dingdang.log' 读取数据: 没有那个文件或目录
tail: 没有剩余文件
pi@raspberrypi:~ $ sudo nano /temp/dingdang.log
pi@raspberrypi:~ $ dir
Desktop  dingdang  Documents  Downloads  g014b2b  Music  Pictures  Public  python_games  Templates  Videos
pi@raspberrypi:~ $ cd dingdang
pi@raspberrypi:~/dingdang $ dir
boot       client  _config.yml  launcher  LICENSE  README.md  temp      tests
Camera.py  CNAME   dingdang.py  _layouts  login    static     temp.wav  test.sh
pi@raspberrypi:~/dingdang $ cd temp
pi@raspberrypi:~/dingdang/temp $ dir
account_info.json                            ali-tts8f38d69e892f87bf094bde23691c2d29.mp3
ali-tts01c1b521d31662e99f42d6f67febfa34.mp3  ali-tts93721b6ae8d250d5916fd3b2074c8828.mp3
ali-tts03812bd784e6e71b280a54dd2ac16455.mp3  ali-tts975d94937f1f1ce23da4eb8ae029cbba.mp3
ali-tts07822286e2d7eb9c5c385596cdad8fcb.mp3  ali-tts98a485b7521ca7806ad6aca459b82d6f.mp3
ali-tts0a44c1c015363ed8006f6417f614e9ff.mp3  ali-tts9be47b980a683b5d66c553b27a948bb1.mp3
ali-tts0cfae383362bc63d7ac429a5755fef05.mp3  ali-tts9fde29a5cc70bac2f2c50a893e0bbab5.mp3
ali-tts0f674cf88f4de52bd47bd0ed0faa2421.mp3  ali-ttsab780a6f74cb9472565b2722d485067d.mp3
ali-tts13aac74987d9899e7b73166124f6c388.mp3  ali-ttsac704cbe75409da75079e99d7ad92d65.mp3
ali-tts155a0788c068cb4e6d2463bd6285a4a4.mp3  ali-ttsb0f993cd72dd2d60c8a3f47d117ad8a7.mp3
ali-tts16815254531798dc21ee979d1d9c6675.mp3  ali-ttsc32bd3a3df6c58141d698ec0547118d8.mp3
ali-tts17663f88104d7d38fb630c49114e152b.mp3  ali-ttsc7028a6c115383985c69b2fb51591d66.mp3
ali-tts1a93b7dee270802611cc7b19f99b3b71.mp3  ali-ttsc7a4f8a9a4dc5e4d78b1b38d65a2d43c.mp3
ali-tts1e749725d795301eb9bbc4a761b1095d.mp3  ali-ttscbc75e8f6d22831623b999f83c24f014.mp3
ali-tts1f87f675d8555cdcb432c7a091178ca3.mp3  ali-ttsce65dc7dce4d362aad59e7082de6d61c.mp3
ali-tts202cb962ac59075b964b07152d234b70.mp3  ali-ttscfa51798ed02900a6894efb92f735779.mp3
ali-tts21b05543a848405475fb243b067c3732.mp3  ali-ttsd3008d4c617dc97b280ac51e905a87d9.mp3
ali-tts224be4a2887086d65e2c763bf52193a6.mp3  ali-ttsd3b086383fac753c9dfbc03575d5c37e.mp3
ali-tts22c0d48f6faf33b08ed3a8631237cbd2.mp3  ali-ttsd9809aa2314d74ed043615fbaccab9e5.mp3
ali-tts239b38a68f9fa4effbc575048367c73f.mp3  ali-ttsdaeb65f00d5703f1f39ade91c5190a8d.mp3
ali-tts23cd6ef66069baee1267fdb6820017a6.mp3  ali-ttsdf4e0f8de02506c625525e3573e3dc42.mp3
ali-tts279349360034da3275b4d8f81a0c5bfb.mp3  ali-ttse0deff349b2c61f5f796ccaa344a4930.mp3
ali-tts35eccea7f8939db7cfcaedbd2083e548.mp3  ali-ttse216e165a9dbcb958144caa4dbff1f69.mp3
ali-tts48af4341f745163f945fa838eeabb062.mp3  ali-ttse4f58a805a6e1fd0f6bef58c86f9ceb3.mp3
ali-tts4e66045d38dfa3f165942c0c6197cc41.mp3  ali-ttse7dab11420c226a541b988e00045c4c8.mp3
ali-tts54ab88728d85dc23cbeb72bc7ed3431f.mp3  ali-ttse8f6c9b9d29c099a217a170dd91e04ab.mp3
ali-tts5a41c967da367a45746867fd0cc77cb5.mp3  ali-ttsec885ffe3eb65954a180738c2460cd90.mp3
ali-tts5ac03a5f0207dda96cb7b06c569189ab.mp3  ali-ttsf0dc3be4cdb369467370a5e7520823fc.mp3
ali-tts5bd3756e7580d0a2e5318bcdd0017719.mp3  ali-ttsf5e14cf795e3b873ca017a5d582d60de.mp3
ali-tts6111d148b06192abcc60546ffd73420e.mp3  ali-ttsf6c656f8c98eaaa958af645a01d40c2b.mp3
ali-tts62309c5185498cadb708ae375a1b85cb.mp3  ali-ttsf71a351762b4b6c483fbaabe7e835f08.mp3
ali-tts692e92669c0ca340eff4fdcef32896ee.mp3  ali-ttsf97261b2cbf14ca620f893b9cf68915d.mp3
ali-tts716483482c284093570c8387256a1206.mp3  ali-ttsff4a71978859e1d4915a7f18cac18857.mp3
ali-tts71fa3bd0e5368dfd7865a5f1c67f4f91.mp3  contact_list.json
ali-tts72b302bf297a228a75730123efef7c41.mp3  contacts.json
ali-tts7647966b7343c29048673252e490f736.mp3  dingdang.log
ali-tts7c8e93a20d4acb461c720c7b7094aaba.mp3  group_list.json
ali-tts7f8cbeaf9a69f9216501db4a33d09588.mp3  group_users.json
ali-tts82cc64a3838722e76e8ededc5e67d5d3.mp3  member_list.json
ali-tts849df1d6b40fafaa808a6c392435d706.mp3  public_list.json
ali-tts86281a371d722a47e8edda417060e257.mp3  special_list.json
ali-tts8bd88545bede4e355d5dcc34375aa0bb.mp3  voice_3420205069983177532.mp3
ali-tts8bf726789c738ed178f31f957b79f6c7.mp3  voice_3420205069983177532.wav

**Comment by chinaboy2277** [comment]
dingdang.log 是刚刚创建的

**Comment by chinaboy2277** [comment]
已经解决，添加插件格式不对，希望能改正

**Comment by wzpan** [comment]
问题是因为你用过root启动过dingdang-robot导致dingdang.log是root文件，普通用户没法访问。

sudo 删掉这个文件，重新启动dingdang即可。
