### ISSUE TITLE
gzip: dingdang-respeaker-2017-11-06.img: No space left on device

### ISSUE THREAD

**Issue by guowei1651** [dingdang-robot/dingdang-robot#31]
16G的TF。还剩下8G多。解码的时候就是包没有空间。

**Comment by wzpan** [comment]
1. 如果是TF卡，刷完显示全部只有8G空间，你需要扩展下磁盘：

终端执行 `raspi-config` 进入树莓派命令，进入 Advanced Options ，开启 Expand File System，扩展您的 Micro-SD 卡空间（否则刷完只有 8G 容量）

2. 如果是空间不够，自行解决下。看看是不是你开启了录像之类的导致空间爆了。

**Comment by guowei1651** [comment]
在win上解压镜像文件，在树莓派上解压镜像文件。不管多大的剩余空间都报没有空间。

**Comment by wzpan** [comment]
为什么要在树莓派上解压镜像文件？不是这么烧录镜像的。请参考 [镜像安装说明](https://github.com/dingdang-robot/dingdang-robot/wiki/install#%E9%95%9C%E5%83%8F%E5%AE%89%E8%A3%85) 。
