### ISSUE TITLE
AttributeError:'Brain' object has no attribute 'profile'

### ISSUE THREAD

**Issue by mbyase** [dingdang-robot/dingdang-robot#43]
运行后，提示AttributeError:'Brain' object has no attribute 'profile'错误

**Comment by wzpan** [comment]
没遇到过这个问题。你有没有改过源码？

`git log` 确认下你当前的dingdang-robot是什么时候的版本。

**Comment by wzpan** [comment]
@Seanseattle 这个问题应该是已经修复了。请问是用的哪个分支？`git pull` 更新下试试？

**Comment by Steve0x2a** [comment]
@wzpan respeaker分支下依然有此问题

**Comment by goinni** [comment]
[ERROR] Except in proc_msg
In:0.00% 00:00:26.28 [00:00:00.00] Out:1.16M [-=====|=====-] Hd:3.0 Clip:0    Traceback (most recent call last):
  File "/home/pi/dingdang/client/wxbot.py", line 822, in proc_msg
    res = self.check_msg()
  File "/home/pi/dingdang/client/wxbot.py", line 787, in check_msg
    self.handle_msg(r)
  File "/home/pi/dingdang/client/wxbot.py", line 767, in handle_msg
    self.handle_msg_all(message)
  File "/home/pi/dingdang/client/WechatBot.py", line 35, in handle_msg_all
    profile = self.brain.profile
AttributeError: 'Brain' object has no attribute 'profile'



有解决办法吗，调了好久，微信发指令不好用，但能收到，发信息就报错

**Comment by wzpan** [comment]
抱歉拖这么久才修复，已解决。
