### ISSUE TITLE
可以唤醒但无法识别语音

### ISSUE THREAD

**Issue by Polynomia** [dingdang-robot/dingdang-robot#50]
您好！我使用的是3.5mm输出和usb麦克风，配置使用默认的，改动的地方有语音识别和合成使用阿里云。已经在配置中修改成了自己的access key。还有聊天机器人，我也修改成了自己的图灵机器人api key，并在配置中设置了。
运行dingdang.py时，唤醒没有问题，可以听到滴滴的响应声。但无法识别我说了什么，请问这个问题要怎么解决呢？

![image](https://user-images.githubusercontent.com/26021091/40348922-9f2ef68a-5dd7-11e8-82b5-fccd68e2afac.png)

运行dingdang.py的输出如下：

![image](https://user-images.githubusercontent.com/26021091/40349032-ee24b48c-5dd7-11e8-9b07-c34df2d6a63b.png)

于是我准备使用默认配置中的讯飞语音，但是在运行dingdang.py时会报错。如下：

![image](https://user-images.githubusercontent.com/26021091/40348993-cccbe72e-5dd7-11e8-8e68-2e3a88528c5f.png)

因为是第一次使用叮当，求赐教，万分感谢！

**Comment by erlang779** [comment]
大兄弟问题解决了吗 我也遇到了这个问题

**Comment by wzpan** [comment]
@erlang779 常见问题：https://github.com/dingdang-robot/dingdang-robot/wiki/troubleshooting#%E5%90%AF%E5%8A%A8%E6%8A%A5%E9%94%99
