### ISSUE TITLE
如何进入debug模式

### ISSUE THREAD

**Issue by eaglekeen** [dingdang-robot/dingdang-robot#53]
现在叮当当我说完指令，在说语音能识别但是总说：请按规定的要求进行加密，我单独运行diagnose。py,总报错说 
File "diagnose.py", line 11, in <module>
    from . import dingdangpath
ValueError: Attempted relative import in non-package
我diagnose。py和dingdangpath.py也是在同一文件夹，不知道怎么回事，还请大神指教。

**Comment by wzpan** [comment]
``` sh
python dingdang.py --debug --verbose
```
