### ISSUE TITLE
在微信发送信息的时候,到机器人接口的内容会带 {主人名称}说:

### ISSUE THREAD

**Issue by zanjie1999** [dingdang-robot/dingdang-robot#55]
刚刚才发现搬来这里了...还以为已经不维护了...
在微信发送信息的时候
到图灵机器人接口的内容会带
 {主人名称}说:

例如:
在微信发送: 
今天天气怎么样

图灵后台看到接口调用时收到的信息内容是: 
小主人说:今天天气怎么样

如果语音唤醒没有这个问题
(我设置的主人的名字是"小主人")

**Comment by wzpan** [comment]
没听懂这是什么问题呢……

**Comment by zanjie1999** [comment]
终于抽空出来搞一下
刚刚 git pull 一次之后微信登陆没问题了
继续说下这个问题
具体的话看一下这些图
![4.png](https://i.loli.net/2018/06/13/5b2121370f578.png)
![1.jpg](https://i.loli.net/2018/06/13/5b2121371bf2e.jpg)
![2.jpg](https://i.loli.net/2018/06/13/5b21213740560.jpg)
![3.jpg](https://i.loli.net/2018/06/13/5b2121376f96a.jpg)

**Comment by wzpan** [comment]
@zanjie1999 抱歉拖这么久才修复，已经解决了。
