### ISSUE TITLE
请问插件可以写定时任务么

### ISSUE THREAD

**Issue by andy2080** [dingdang-robot/dingdang-robot#69]
请问插件可以写定时任务么。
想在叮当上扩展服务器监控，出现意外情况推送语音报警。需要用到定时任务，目前从叮当的文件上只看有个 EMAIL 的定时，2分钟执行一次，是否需要在该文件上修改还是插件也可以做到定时任务

**Comment by wzpan** [comment]
其实 [notifier](https://github.com/dingdang-robot/dingdang-robot/blob/master/client/notifier.py) 也是一个可扩展的东西，只是我没有暴露出接口。你可以仿照着添加一个新的 notifier 去执行一些自动化任务。
