### ISSUE TITLE
有计划加入带娃功能吗？

### ISSUE THREAD

**Issue by lightjl** [dingdang-robot/dingdang-robot#70]
比如听到小孩哭，就放歌、讲故事，通知家长之类的。

**Comment by wzpan** [comment]
这个功能并不适用于通用化的dingdang-robot，而更适合拿dingdang-robot做二次改造。比如加入传感器检测哭声然后触发插件。

**Comment by lightjl** [comment]
@wzpan 触发插件，好像官方的做法只能定义词语唤醒．想问下要想用哭声唤醒，是改写Brain这个类吗？还是说写个小程序，把哭声直接翻译成＂宝宝哭了＂，然后有＂宝宝哭了＂做唤醒词好？

**Comment by wzpan** [comment]
@lightjl 你说的这个方案不见得现有的唤醒词能适用，因为唤醒词通常都是针对文字的，而宝宝的哭声是非文字形式的。比较合适的可能是用传感器之类的装置，对一定的频率进行监视。不过误唤醒率不好说。
