### ISSUE TITLE
没反应

### ISSUE THREAD

**Issue by lvwuyunlifan** [dingdang-robot/dingdang-robot#8]
我是下载dingdang镜像，然后按照配置完成的，开机的时候听到叮当说话了“XX我能为你做什么”，但是我呼叫叮当的时候，没有反应，这是什么原因呢?

**Comment by NeXT286** [comment]
遵循“配置”中页面的设置声卡走一遍试试
因为可能录音设备或者播放器没设置好，录音试试就知道了
或者重新安装sox

**Comment by wzpan** [comment]
唤醒了没？
