### ISSUE TITLE
Wiki 里手动安装的 repo 地址尚未更新

### ISSUE THREAD

**Issue by satoi8080** [dingdang-robot/dingdang-robot#94]
https://github.com/dingdang-robot/dingdang-robot/wiki/install#手动安装

这里的repo地址依然是原来 @wzpan 的repo https://github.com/wzpan/dingdang-robot.git

应当更新到https://github.com/dingdang-robot/dingdang-robot.git

（没能找到Wiki页面的编辑功能，fork之后Wiki也消失，所以没能以pull request的方法帮你修改）

**Comment by wzpan** [comment]
@satoi8080 谢谢提醒，已修改 👍
