### ISSUE TITLE
win7 电脑没有 树莓设备,能不能运行起来? 用微信测试 语音和对话api?

### ISSUE THREAD

**Issue by ithjz** [dingdang-robot/dingdang-robot#99]
win7 电脑没有 树莓设备,能不能运行起来? 用微信测试 语音和对话api?

**Comment by wzpan** [comment]
不建议在windows里折腾，太多linux only的库在windows里是没法支持的。

**Comment by ithjz** [comment]
那我可以直接在,centos7里弄了吗? 有文档吗url?
